export enum AlertType {
    ALERT_UNKNOWN       = "ALERT_UNKNOWN",
    ALERT_START         = "ALERT_START",
    ALERT_STOP          = "ALERT_STOP",
    ALERT_ENGINE_START  = "ALERT_ENGINE_START",
    ALERT_ENGINE_STOP   = "ALERT_ENGINE_STOP",
    ALERT_OVER_SPEED    = "ALERT_OVER_SPEED",
    ALERT_GEOFENCE_IN   = "ALERT_GEOFENCE_IN",
    ALERT_GEOFENCE_OUT  = "ALERT_GEOFENCE_OUT",
    ALERT_IGNITION_ON   = "ALERT_IGNITION_ON",
    ALERT_IGNITION_OFF  = "ALERT_IGNITION_OFF",
    ALERT_FUEL_DROP     = "ALERT_FUEL_DROP",
    ALERT_FUEL_FILL     = "ALERT_FUEL_FILL",
}
